"""add raw file fields to artwork_images

Revision ID: 1023370cb824
Revises: 45c09593b0be
Create Date: 2026-03-22 20:54:25.382761

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1023370cb824"
down_revision: str | None = "45c09593b0be"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("artwork_images", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("url_raw", sa.String(length=2048), nullable=False, server_default="")
        )
        batch_op.add_column(
            sa.Column("storage_path_raw", sa.String(length=1024), nullable=False, server_default="")
        )
        batch_op.add_column(sa.Column("raw_expires_at", sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("artwork_images", schema=None) as batch_op:
        batch_op.drop_column("raw_expires_at")
        batch_op.drop_column("storage_path_raw")
        batch_op.drop_column("url_raw")

    # ### end Alembic commands ###
