"""add_friend_links_table

Revision ID: 1eb341faa705
Revises: daebc514a259
Create Date: 2026-03-23 03:15:04.186204

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1eb341faa705"
down_revision: str | None = "daebc514a259"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "friend_links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("avatar_url", sa.String(length=2048), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("friend_links", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_friend_links_enabled"), ["enabled"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_friend_links_sort_order"), ["sort_order"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("friend_links", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_friend_links_sort_order"))
        batch_op.drop_index(batch_op.f("ix_friend_links_enabled"))

    op.drop_table("friend_links")
    # ### end Alembic commands ###
