"""add artwork_sources and phash

Revision ID: 45c09593b0be
Revises: 973cfca7611c
Create Date: 2026-03-19 09:19:59.817681

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "45c09593b0be"
down_revision: str | None = "973cfca7611c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artwork_sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("artwork_id", sa.Integer(), nullable=False),
        sa.Column("platform", sa.String(length=50), nullable=False),
        sa.Column("pid", sa.String(length=255), nullable=False),
        sa.Column("source_url", sa.String(length=2048), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("raw_info", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["artwork_id"], ["artworks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("platform", "pid", name="uq_sources_platform_pid"),
    )
    with op.batch_alter_table("artwork_sources", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_artwork_sources_artwork_id"), ["artwork_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_artwork_sources_platform"), ["platform"], unique=False)

    # Migrate existing artworks → primary sources
    conn = op.get_bind()
    conn.execute(
        sa.text("""
        INSERT INTO artwork_sources
            (artwork_id, platform, pid, source_url, is_primary, raw_info, created_at)
        SELECT id, platform, pid, source_url, 1, raw_info, created_at
        FROM artworks
    """)
    )

    with op.batch_alter_table("artwork_images", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("phash", sa.String(length=16), nullable=False, server_default="")
        )
        batch_op.create_index(batch_op.f("ix_artwork_images_phash"), ["phash"], unique=False)

    with op.batch_alter_table("artworks", schema=None) as batch_op:
        batch_op.drop_constraint("uq_artworks_platform_pid", type_="unique")
        batch_op.drop_column("raw_info")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("artworks", schema=None) as batch_op:
        batch_op.add_column(sa.Column("raw_info", sa.TEXT(), nullable=False))
        batch_op.create_unique_constraint(
            batch_op.f("uq_artworks_platform_pid"), ["platform", "pid"]
        )

    with op.batch_alter_table("artwork_images", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_artwork_images_phash"))
        batch_op.drop_column("phash")

    with op.batch_alter_table("artwork_sources", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_artwork_sources_platform"))
        batch_op.drop_index(batch_op.f("ix_artwork_sources_artwork_id"))

    op.drop_table("artwork_sources")
    # ### end Alembic commands ###
