"""add_title_zh_to_artworks

Revision ID: 527724bb0d1d
Revises: 1eb341faa705
Create Date: 2026-03-23 04:01:20.173330

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "527724bb0d1d"
down_revision: str | None = "1eb341faa705"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("artworks", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("title_zh", sa.String(length=500), nullable=False, server_default="")
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("artworks", schema=None) as batch_op:
        batch_op.drop_column("title_zh")

    # ### end Alembic commands ###
