"""add tag_types table

Revision ID: 973cfca7611c
Revises: bcc6fe9f6022
Create Date: 2026-03-19 08:00:01.942619

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "973cfca7611c"
down_revision: str | None = "bcc6fe9f6022"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Create tag_types table (if_not_exists for idempotency after partial runs)
    conn = op.get_bind()
    table_exists = sa.inspect(conn).has_table("tag_types")

    if not table_exists:
        op.create_table(
            "tag_types",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("name", sa.String(length=50), nullable=False),
            sa.Column("label", sa.String(length=100), nullable=False),
            sa.Column("color", sa.String(length=50), nullable=False),
            sa.Column("sort_order", sa.Integer(), nullable=False),
            sa.PrimaryKeyConstraint("id"),
        )
        with op.batch_alter_table("tag_types", schema=None) as batch_op:
            batch_op.create_index(batch_op.f("ix_tag_types_name"), ["name"], unique=True)

        # Seed default tag types before adding FK
        tag_types = sa.table(
            "tag_types",
            sa.column("id", sa.Integer),
            sa.column("name", sa.String),
            sa.column("label", sa.String),
            sa.column("color", sa.String),
            sa.column("sort_order", sa.Integer),
        )
        op.bulk_insert(
            tag_types,
            [
                {"name": "general", "label": "General", "color": "neutral", "sort_order": 0},
                {"name": "character", "label": "Character", "color": "green", "sort_order": 1},
                {"name": "artist", "label": "Artist", "color": "orange", "sort_order": 2},
                {"name": "meta", "label": "Meta", "color": "purple", "sort_order": 3},
            ],
        )

    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.create_foreign_key("fk_tags_type_tag_types", "tag_types", ["type"], ["name"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.drop_constraint("fk_tags_type_tag_types", type_="foreignkey")

    with op.batch_alter_table("tag_types", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tag_types_name"))

    op.drop_table("tag_types")
    # ### end Alembic commands ###
