"""add bot_post_queue table

Revision ID: daebc514a259
Revises: c3d4e5f6a1b2
Create Date: 2026-03-23 02:47:26.493565

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "daebc514a259"
down_revision: str | None = "c3d4e5f6a1b2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bot_post_queue",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("artwork_id", sa.Integer(), nullable=False),
        sa.Column("platform", sa.String(length=50), nullable=False),
        sa.Column("channel_id", sa.String(length=255), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("added_by", sa.String(length=255), nullable=False),
        sa.Column("added_by_user_id", sa.Integer(), nullable=True),
        sa.Column("error", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["added_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["artwork_id"], ["artworks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("bot_post_queue", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_bot_post_queue_artwork_id"), ["artwork_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_bot_post_queue_priority"), ["priority"], unique=False)
        batch_op.create_index(batch_op.f("ix_bot_post_queue_status"), ["status"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bot_post_queue", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bot_post_queue_status"))
        batch_op.drop_index(batch_op.f("ix_bot_post_queue_priority"))
        batch_op.drop_index(batch_op.f("ix_bot_post_queue_artwork_id"))

    op.drop_table("bot_post_queue")
    # ### end Alembic commands ###
